<?php
namespace app\admin\controller;


use app\admin\logic\Login;
use think\Config;
use think\Controller;
use think\Loader;
use think\Request;
use think\Session;

class Index extends Controller
{
    public function _initialize()
    {

        //初始化方法
        parent::_initialize();
        // TODO: Change the autogenerated stub
        $login = Loader::model('login', 'logic');
        if ($login->isLoginTrue()) {
            //正常进行
        } else {
            $this->error('你还没有登录', '/admin/login/index');
            return false;
        }
    }


    public
    function index()
    {
        return $this->fetch();//渲染模板有两种方式    return $view();
    }

    public
    function tosuccess()
    {
        $this->success('成功啦', 'index/index', '咚咚咚', 10);
    }

    public
    function toerror()
    {
        $this->error('出错拉！！', 'index/index');
    }

//空操作当没有以上方法时走此方法，可以获取到方法位置的名称，
    public
    function _empty(Request $request)
    {
        $this->error('方法' . $request->action() . '不存在');

    }
}
