<?php
/**
 * Created by PhpStorm.
 * User: qinxy
 * Date: 2017/3/1
 * Time: 20:48
 */
namespace app\admin\login;

use think\Model;

class Leader extends Model
{

    protected function initialize()
    {
        parent::initialize();
        // TODO: Change the autogenerated stub
    }

    public function inedx()
    {

    }
}