<?php
/**
 * Created by PhpStorm.
 * User: qinxy
 * Date: 2017/3/1
 * Time: 20:48
 */
namespace app\admin\logic;


use app\admin\model\Limit;

use think\Model;
use think\Request;

class Leader extends Model
{

    protected function initialize()
    {
        parent::initialize();
        // TODO: Change the autogenerated stub
    }

    public function checkLimit()
    {
        $request = Request::instance();
        $limit=Limit::all();
    }

}