<?php
/**
 * Created by PhpStorm.
 * User: qinxy
 * Date: 2017/3/1
 * Time: 20:48
 */
namespace app\admin\logic;


use app\admin\model\Limit;

use think\Db;
use think\Model;
use think\Request;

class Leader extends Model
{

    protected function initialize()
    {
        parent::initialize();
        // TODO: Change the autogenerated stub
    }

    public function checkLimit()
    {
        $request = Request::instance();
        $limit = Limit::all();
    }

    public function clearUpTypeName($typeName = 1)
    {
        $res = [];
        for ($i = 1; $i < 4; $i++) {
            if($typeName==$i){
                $res[]=[
                    'select'=>'true'
                ];
            }else{
                $res[]=[
                    'select'=>'false'
                ];
            }
        }
    }

}