<?php
/**
 * Created by PhpStorm.
 * User: 12156
 * Date: 2017/2/18
 * Time: 20:50
 */
namespace app\admin\logic;


use think\Cookie;
use think\Db;
use think\Loader;
use think\Model;
use think\Request;
use think\Session;

class Login extends Model
{

    protected function initialize()
    {
        parent::initialize();
        // TODO: Change the autogenerated stub


    }

    public function outLogin()
    {
        Session::delete('admin_userid');
        Cookie::delete('admin_userid');
        return true;


    }

//验证加写入session与cookie
    public function testAll()
    {
        $validate = Loader::validate('User');
        $request = Request::instance();
        $data = [
            'name' => $request->param('name'),
            'password' => $request->param('password'),
            'captcha' => $request->param('captcha')
        ];

        if (!$validate->check($data)) {
            $errorJson = [
                'code' => 1,
                'message' => $validate->getError()
            ];

            return $errorJson;
        } else {
            $successJson = [
                'code' => 0,
                'message' => '验证成功立刻跳转'
            ];
            return $successJson;

        }
    }

//登录注入数据
    function chengLogin()
    {
        $request = Request::instance();
        $theUser = Db::table('cms_user')->where(['user_name' => $request->param('name'), 'user_password' => md5($request->param('password'))])->find();
        if ($theUser) {
            Session::set('admin_userid', $theUser['id'] );

            Cookie::set('admin_userid', $theUser['id'], config('use_limit_time'));
        }
    }

//判断是否登陆中
    public function isLoginTrue()
    {
        $sessionUserId = Session::get('admin_userid');
        $cookieUserId = Cookie::get('admin_userid');
        if ($sessionUserId != 0 && $sessionUserId == $cookieUserId) {
            Cookie::set('userid', Cookie::get('userid'), config('use_limit_time'));

            return true;
        } else {
            $this->outLogin();
            return false;
        }
    }

}