<?php
/**
 * Created by PhpStorm.
 * User: 12156
 * Date: 2017/2/18
 * Time: 20:50
 */
namespace app\admin\logic;

use think\Loader;
use think\Model;
use think\Request;
use think\Session;

class Login extends Model
{

    protected function initialize()
    {
        parent::initialize();
        // TODO: Change the autogenerated stub
        $this->isLoginTrue();

    }

    /**
     * 验证成功重定向到admin首页
     */
    public function toAdmin()
    {
        redirect('admin/index/index');
    }


    public function testAll()
    {
        $reguest = Request::instance();
        $data=[
            'name'=>$reguest->param('name'),
            'password'=>$reguest->param('password'),
            'captcha'=>$reguest->param('captcha')
        ];
        $validate=Loader::validate('user');
        if(!$validate->check($data)){
            dump($validate->getError());
        }
        if ($reguest->has('name') && $reguest->has('password')) {

        } else {
            $error=Loader::model('error','service');
            $ajaxArray = array('code'=>1,'message'=>$error->getMessage(1),'date'=>'');
            return;
        }
    }

    public function isLoginTrue()
    {
        Session::prefix('admin');
        $sessionUserId = Session::get('userId');
        if ($sessionUserId != 0) {
            $this->toAdmin();
            return true;
        } else {
            return false;
        }
    }

}