<?php
/**
 * Created by PhpStorm.
 * User: 12156
 * Date: 2017/2/18
 * Time: 20:50
 */
namespace app\admin\logic;

use app\admin\model\User;
use think\Cookie;
use think\Loader;
use think\Model;
use think\Request;
use think\Session;

class Login extends Model
{

    protected function initialize()
    {
        parent::initialize();
        // TODO: Change the autogenerated stub
        $this->isLoginTrue();

    }

    /**
     * 验证成功重定向到admin首页
     */
    public function toAdmin()
    {
        redirect('admin/index/index');
    }

//验证加写入session与cookie
    public function testAll()
    {
        $validate = Loader::validate('User');
        $request = Request::instance();
        $data = [
            'name' => $request->param('name'),
            'password' => $request->param('password'),
            'captcha' => $request->param('captcha')
        ];

        if (!$validate->check($data)) {
            $errorJson = [
                'code' => 1,
                'message' => $validate->getError()
            ];

            return $errorJson;
        } else {
            $successJson = [
                'code' => 0,
                'message' => '验证成功立刻跳转'
            ];
            return $successJson;

        }
    }

    public function isLoginTrue()
    {
        Session::prefix('admin');
        $sessionUserId = Session::get('userid');
        Cookie::prefix('admin');
        $cookieUserId = Cookie::get('userid');
        if ($sessionUserId != 0 && $sessionUserId == $cookieUserId && $cookieUserId != 0) {

            return true;
        } else {
            return false;
        }
    }

}